### ISSUE TITLE
Inactive budgets break the app

### ISSUE THREAD

**Issue by dkisselev** [tomcheng/budget-reports#1]
I have an older budget in my repo that hasn't been used in over a year.

The app fails to find categories for the current month as it iterates over the budget and completely fails out: 

```
TypeError: Cannot read property 'categories' of undefined
    at d (repoUtils.js:33)
    at formatter (ynabRepo.js:62)
    at repoUtils.js:17
    at App.js:61
    at Array.forEach (<anonymous>)
    at e.<anonymous> (App.js:60)
    at pe (react-dom.production.min.js:107)
    at commitLifeCycles (react-dom.production.min.js:159)
    at w (react-dom.production.min.js:185)
    at x (react-dom.production.min.js:182)
```

It seems that deleting budgets the YNAB's UI also doesn't hide them from API apps (at least not immediately, there's probably a queue or some other cleanup scripts that runs and eventually purges old budgets)

**Comment by dkisselev** [comment]
No rush, it looks like the budget did get deleted eventually but this issue will probably come up for others with multiple budgets as well.

**Comment by tomcheng** [comment]
I've updated the app to only fetch budget details when you're viewing that budget and also added an error boundary around the entire App, so at least JS errors should've break the app entirely. Thanks again @dkisselev!
