### ISSUE TITLE
Overspending is [literally] off the charts

### ISSUE THREAD

**Issue by dkisselev** [tomcheng/budget-reports#2]
Progress bars for any categories that are super overspent will explode past the intended container.

Although comical, it's probably an unintended "feature".

Maybe turning the progress bar red would be a good indicator that the category is overspent. An indicator like "1.5x" next to it might also be helpful to show how overspent the category is.

![image](https://user-images.githubusercontent.com/945848/41929350-971ad480-792c-11e8-8c37-2e7718658346.png)

**Comment by tomcheng** [comment]
Ah nice catch, I've made the width capped at 100% and turned the bar red when it's overspent.
Thanks for reporting this!
