### ISSUE TITLE
Projections without a mortgage account

### ISSUE THREAD

**Issue by dkisselev** [tomcheng/budget-reports#5]
The app currently crashes on budgets that don't have mortgage accounts.

The getMortgageRates projectionUtil returns null when there are no accounts but ProjectionsBody expects an object with parameters that it attempts to assign elsewhere.

```
Uncaught TypeError: Cannot read property 'paymentsLeft' of null
    at ProjectionsBody.js:57
    ...
```

Thanks for all your great work so far.

**Comment by tomcheng** [comment]
Ah thanks for the issue, this should be fixed now! YNAB also changed the way they categorize their accounts, so I've started to add a settings page (cog on the side menu) where you indicated which accounts are mortgage and which accounts are investments.
