### ISSUE TITLE
Duplicate Transactions for Rescheduled Transaction 

### ISSUE THREAD

**Issue by ardimaunahan** [tomcheng/budget-reports#9]
I notice that when a scheduled transaction arrived and then I reschedule it to a future date, it causes duplicates. Please check if this a bug in the budget-reports or a YNAB API issue.

**Comment by tomcheng** [comment]
Hi @ardimaunahan, thanks for the reporting the issue! It looks like the app wasn't filtering out deleted transactions. That should be fixed now, and hopefully that addresses rescheduled transactions as well.
